# Generated by Django 6.0 on 2025-12-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmonaut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО космонавта')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('birth_place', models.CharField(max_length=300, verbose_name='Место рождения')),
                ('first_flight', models.DateField(verbose_name='Первый полет')),
                ('total_flights', models.IntegerField(verbose_name='Количество полетов')),
                ('total_space_time', models.CharField(max_length=100, verbose_name='Общее время в космосе')),
                ('eva_count', models.IntegerField(default=0, verbose_name='Выходы в открытый космос')),
                ('eva_time', models.CharField(blank=True, max_length=100, verbose_name='Время в открытом космосе')),
                ('achievements', models.TextField(verbose_name='Достижения и рекорды')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, upload_to='cosmonauts/', verbose_name='Фотография')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Космонавт',
                'verbose_name_plural': 'Космонавты',
                'ordering': ['order'],
            },
        ),
    ]
